spring:
  application:
    name: bird-user
  #json序列化统一时间格式处理
  jackson:
    date-format: yyyy-MM-dd:HH:mm:ss
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${virtual.machine.ip}:3306/bird_db_user?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  redis:
    host: 192.168.198.132
    port: 6379
  cloud:
    #nacos配置
    nacos:
      discovery:
        #如果是集群搭建，这里配置成Nginx的地址即可或者填写一个集群下多个nacos地址（类似于Eureka集群配置）
        server-addr: ${virtual.machine.ip}:8848
      config:
        max-retry: 10
    #sentinel配置
    sentinel:
      transport:
        dashboard: ${virtual.machine.ip}:8858 #sentinel地址
        port: 8719
      #Sentinel持久化配置
      datasource:
        ds1:
          nacos:
            server-addr: ${virtual.machine.ip}:8848
            dataId: bird-user-config
            groupId: CONFIG_GROUP
            data-type: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*'

#MP逻辑删除配置
mybatis-plus:
  #控制台输出sql语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#日志配置
logging:
  level:
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    path: F:/log/bird-shop


#设置超时时间openFeign默认集成了ribbon
ribbon:
  #服务调用超时时间
  ReadTimeout: 8000
  #服务连接超时时间
  ConnectTimeout: 8000

#openFeign默认集成了Hystrix
feign:
  hystrix:
    enabled: false

#Hystrix配置
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true #设置是否开启超时 默认true
        isolation:
          strategy: THREAD #设置隔离方式为线程隔离
          thread:
            timeoutInMilliseconds: 8000 #Hystrix的超时时间 默认1000 1s
      #下面配置表示10秒内如果失败的请求次数/20>50%那么开启服务熔断
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 20 #请求次数 默认20
        sleepWindowInMilliseconds: 5 # 时间窗口 默认5秒
        errorThresholdPercentage: 50 #失败率 默认50
  threadpool:
    default:
      coreSize: 50 #配置线程池大小, 默认值10个

#虚拟机ip地址
virtual:
  machine:
    ip: 192.168.198.132

